mesh_density: COARSE
parameters_file: parameters.txt
output_dir: results
running_on : Xenosim
status_check_frquency_in_min : 1
generate_parameters_file: true

parameters_generation:
  power:
    min: 125
    max: 225
    steps: 3 # Number of steps
  speed:
    min: 0.75
    max: 2.25
    steps: 4 # Number of steps
  laser_radius: 50e-6

measure:
  y_begin : 100e-6
  y_end : 700e-6
  x_min : 0
  x_max : 0.0002
  cell_size : 2.5e-06
  min_points_per_zrow: 4

surrogate:
  seed: 0
  n_epochs: 5000
  n_divisions_for_prediction: 50
  possible_outputs:
    - W_mean
    - W_std
    - H_mean
    - H_std
    - D_mean
    - D_std
    - porosity_mean
    - porosity_std

environment:
  hostname:  "xenosim"
  run_address: "/home/simon/run/"
  of_location: "$HOME/OpenFOAM/OpenFOAM-v2412/etc/bashrc"

  