'''
License
    This program is free software: you can redistribute it and/or modify 
    it under the terms of the GNU General Public License as published 
    by the Free Software Foundation, either version 3 of the License, 
    or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful, 
    but WITHOUT ANY WARRANTY; without even the implied warranty of 
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
    
    See the GNU General Public License for more details. You should have 
    received a copy of the GNU General Public License along with this 
    program. If not, see <https://www.gnu.org/licenses/>. 
    

Purpose:
  Postprocessing script for finished simulation cases using ParaView 
  (pvpython):
  - Performs a mesh-aware continuity check of the single track.
  - If the track is continuous, computes per cross-section metrics:
    W (width), H (track height), H_depth (depth), and Porosity.

Assumptions:
  - ParaView (with pvpython) is installed and accessible in PATH.
  - Simulation results are located in "test_case_i" folders generated by 
  generate_data.py.
  - Case outputs are compatible with laserMeltFoam (OpenFOAM v2412).
  - The computational mesh is regular and its spacing is known, allowing 
  expected cross-sections
    along the track to be enumerated.
  - Within each cross-section, cell volumes are uniform (or accounted for), so 
  that porosity
    computed from cell counts is equivalent to volume fraction.

Method:
  1) Continuity check (mesh-aware):
     - All expected cross-sections are determined from the known mesh spacing.
     - For each cross-section, it is verified whether at least one cell is 
     classified as material.
     - If any expected cross-section contains no material cells, the track is 
     considered 
       non-continuous and no further analysis is performed.
     - The result is saved as a boolean file: "continuous.joblib".

  2) Per cross-section analysis (performed only if the track is continuous) – 
    two-stage workflow:

     Stage A — Row-level processing:
       - Each cross-section (x–z plane at fixed y) is processed row by row 
       (along the z-direction).
       - For each row, the total number of material cells, pore cells, and the 
       horizontal extent of material regions are recorded, among other 
       variables used in the subsequent analysis.
       - This information is collected for all rows across all cross-sections.

     Stage B — Metric computation:
       - Pores are classified as either:
         • Surface pores: located at the topmost layer of the cross-section.
         • Internal pores: located below the top surface layer.

       - **Width (W):**  
         Maximum horizontal extent of the melt pool within the cross-section.  
         If multiple disconnected material regions exist, the largest 
         horizontal span is used.

       - **Track height (H):**  
         Vertical extent of the melt pool, defined based on pore distribution:  
         • If surface pores are present: height = difference between the lowest
         material row and the row where the surface pore begins.  
         • If only internal pores are present (or none): height = difference 
         between the highest and lowest material rows.

       - **Depth (H_depth):**  
         Vertical distance between the lowest material row and the row where 
         the maximum horizontal width occurs (i.e., where the track diameter is
                                              largest).

       - **Porosity:**  
         Fraction of pore volume within the cross-section:  
         Porosity = number of pore cells / (number of pore cells + number of 
                                            material cells).  
         If cell volumes are uniform, this equals (pore volume / 
                                                   total cross-section volume).

     - Metrics are computed for all cross-sections and exported as a CSV file.

Outputs (per test_case_i):
  - continuous.joblib          → Boolean indicating track continuity 
                                 (mesh-aware check).
  - cross_section_metrics.csv  → Per cross-section values of W, H, H_depth, and
  Porosity  (only if the track is continuous).

Authors
    Simon A. Rodriguez, University College Dublin (UCD)
    Petar Cosic, University College Dublin (UCD)
    Tom Flint, University of Manchester
    Philip Cardiff, University College Dublin (UCD)

'''

from src.functions_measure_W_H_D import *
import numpy as np
import input_data
from input_data import *


# source the correct OpenFOAM, based on the system and OF version
hostname, run_address, OF_LOCATION = set_environment_variables()

# Read the operational parameters
parameters = np.loadtxt("./parameters.txt", skiprows=1)

# Count the total number of cases
number_cases = parameters.shape[0]

# Calculate results (width, depth, etc)
for i in range(number_cases):
    name_new_folder = MESH_DENSITY + "/test_case_" + str(i + 1)
    print("\n Measuring geometry-based quantities for test_case_" + str(i + 1))
    terminal(f'cp src/extract* {name_new_folder}/')
    terminal(f'cp src/quantities_from_meltpool.py {name_new_folder}/')
    terminal(f'cp src/functions.py {name_new_folder}/')
    terminal(f'cp input_data.py {name_new_folder}/')
    terminal(f'bash -c "source {OF_LOCATION} && cd {name_new_folder} && pvpython extract_meltpool.py"')
    # terminal(f'cd {name_new_folder} && mkdir images_full_meltpool && mv *png images_full_meltpool/')
    # In case mkdir does not work
    laser_radius_i = parameters[i, 2]/2
    terminal(f'cd {name_new_folder} && mv *png images_full_meltpool/')
    terminal(f'cd {name_new_folder} && rm *.py')    
    calculate_geometry_full_meltpool(name_new_folder, laser_radius_i, CSV_3D = name_new_folder + "/meltpool.csv")
    print("\n Finished measuring geometry-based quantities for test_case_"+ str(i + 1), "\n")

print("Geometry measurement finished.")