#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

cp -r initial 0
runApplication blockMesh 
runApplication setSolidFraction
runApplication decomposePar
#runApplication laserMeltFoam
mpirun -np 10 laserMeltFoam -parallel > log.laserMeltFoam 2>&1
#------------------------------------------------------------------------------
