#!/bin/sh
# All the information about queues can be obtained using 'sinfo'

# Slurm flags
#SBATCH -N 2
#SBATCH --ntasks-per-node 40
#SBATCH -t 80:00:00
#SBATCH --job-name=test80cores_portedcode

# Mail me on job start & end
#SBATCH --mail-user=simon.rodriguezluzardo@ucd.ie
#SBATCH --mail-type=BEGIN,END

cd $SLURM_SUBMIT_DIR

# Load the module for the specific version
export PATH=$HOME/Aplic/local-openmpi/bin:$PATH
export LD_LIBRARY_PATH=$HOME/Aplic/local-openmpi/lib:$LD_LIBRARY_PATH


source /home/people/srodriguez/OpenFOAM/OpenFOAM-v2412/etc/bashrc


# Run simulation in parallel
mpirun -np 80 laserMeltFoam -parallel

# Reconstruct the files
reconstructPar

rm -r processor*
